// Generated by CoffeeScript 1.9.1
(function() {
  var VERSION, getDomain, jsdom, request, zfill;

  VERSION = '0.2.0';

  jsdom = require('jsdom');

  request = require('request');

  zfill = function(n) {
    return ('0' + n).substr(-2);
  };

  getDomain = function(s) {
    switch (s) {
      case 'B':
      case 'sen':
      case 'seoul':
      case '서울':
      case '서울특별시':
        return 'hes.sen.go.kr';
      case 'C':
      case 'pen':
      case 'busan':
      case '부산':
      case '부산광역시':
        return 'hes.pen.go.kr';
      case 'D':
      case 'dge':
      case 'daegu':
      case '대구':
      case '대구광역시':
      case '머구':
      case '대집트':
        return 'hes.dge.go.kr';
      case 'E':
      case 'ice':
      case 'incheon':
      case '인천':
      case '인천광역시':
      case '마계':
        return 'hes.ice.go.kr';
      case 'F':
      case 'gen':
      case 'gwangju':
      case '광주':
      case '광주광역시':
      case '팡주':
        return 'hes.gen.go.kr';
      case 'G':
      case 'dje':
      case 'daejeon':
      case '대전':
      case '대전광역시':
      case '머전':
        return 'hes.dje.go.kr';
      case 'H':
      case 'use':
      case 'ulsan':
      case '울산':
      case '울산광역시':
        return 'hes.use.go.kr';
      case 'I':
      case 'sje':
      case 'sejong':
      case '세종':
      case '세종시':
      case '세종특별자치시':
        return 'hes.sje.go.kr';
      case 'J':
      case 'goe':
      case 'gyeonggi':
      case '경기':
      case '경기도':
        return 'hes.goe.go.kr';
      case 'K':
      case 'gwe':
      case 'gangwon':
      case '강원':
      case '강원도':
        return 'hes.gwe.go.kr';
      case 'M':
      case 'cbe':
      case 'chungbuk':
      case '충북':
      case '충청북도':
        return 'hes.cbe.go.kr';
      case 'N':
      case 'cne':
      case 'chungnam':
      case '충남':
      case '충청남도':
        return 'hes.cne.go.kr';
      case 'P':
      case 'jbe':
      case 'jeonbuk':
      case '전북':
      case '전라북도':
        return 'hes.jbe.go.kr';
      case 'Q':
      case 'jne':
      case 'jeonnam':
      case '전남':
      case '전라남도':
        return 'hes.jne.go.kr';
      case 'R':
      case 'gbe':
      case 'gyeongbuk':
      case '경북':
      case '경상북도':
        return 'hes.gbe.kr';
      case 'S':
      case 'gne':
      case 'gyeongnam':
      case '경남':
      case '경상남도':
        return 'hes.gne.go.kr';
      case 'T':
      case 'jje':
      case 'jeju':
      case '제주':
      case '제주도':
      case '탐라':
      case '탐라국':
        return 'hes.jje.go.kr';
      default:
        return false;
    }
  };

  exports.get = function(school, year, month, callback) {
    var d, domain;
    d = new Date;
    if (!/^[B-KMNP-T][0-9]{9}$/.test(school)) {
      callback("Invalid or unknown code (" + school + ")", null);
      return;
    }
    switch (arguments.length) {
      case 2:
        callback = year;
        year = d.getFullYear();
        month = d.getMonth() + 1;
        break;
      case 4:
        if (!((0 < month && month <= 12))) {
          callback('Invalid month (1-12)', null);
          return;
        }
        break;
      default:
        callback('Invalid argument count', null);
        return;
    }
    domain = getDomain(school[0]);
    request.post({
      url: "http://" + domain + "/sts_sci_md00_001.do",
      form: "schulCode=" + school + "&schulCrseScCode=4&ay=" + year + "&mm=" + (zfill(month))
    }, function(e, r, d) {
      var date, day, doc, i, item, k, len, m, name, q, ref, value, window;
      if (e) {
        return callback("Request failed: " + (e.toString()), null);
      } else {
        console.log(d.length);
        doc = jsdom.jsdom(d, {
          querySelector: true
        });
        window = doc.defaultView;
        r = [];
        q = window.document.querySelectorAll('.tbl_type3 td div');
        for (k = 0, len = q.length; k < len; k++) {
          day = q[k];
          if ((day == null) || !day.innerHTML.indexOf('<br>')) {
            continue;
          }
          day = day.innerHTML.replace(/[①-⑬]/g, '');
          date = day.substr(0, day.indexOf('<br>'));
          item = day.split(/(\[.+?\])/);
          if (date === '') {
            continue;
          }
          r[date] = {};
          for (i = m = 1, ref = item.length - 1; m <= ref; i = m += 2) {
            name = item[i].replace(/(\[|\])/g, '');
            value = item[i + 1].split('<br>').filter(Boolean);
            switch (name) {
              case '조식':
                r[date].breakfast = value;
                break;
              case '중식':
                r[date].lunch = value;
                break;
              case '석식':
                r[date].dinner = value;
            }
          }
        }
        return callback(null, r);
      }
    });
    return void 0;
  };

  exports.find = function(doe, query, callback) {
    var domain;
    domain = getDomain(doe);
    if (!domain) {
      callback("No such dep: " + doe, null);
    }
    request({
      uri: "http://" + domain + "/spr_ccm_cm01_100.do?kraOrgNm=" + (encodeURI(query)),
      json: true
    }, function(e, res, j) {
      var l;
      if (e) {
        callback("Request failed: " + e, null);
        return;
      }
      l = j.resultSVO.orgDVOList;
      return callback(null, l.map(function(o) {
        return {
          name: o.kraOrgNm,
          code: o.orgCode,
          type: o.schulCrseScCodeNm,
          address: o.zipAdres
        };
      }));
    }).on('error', function(e) {
      return callback("Request failed: " + e, null);
    });
    return void 0;
  };

}).call(this);
