// Generated by CoffeeScript 1.8.0
(function() {
  var getDomain, jsdom, request, zfill;

  jsdom = require('jsdom');

  request = require('request');

  jsdom.defaultDocumentFeatures = {
    FetchExternalResources: false,
    ProcessExternalResources: false
  };

  zfill = function(n) {
    return ('0' + n).substr(-2);
  };

  getDomain = function(s) {
    switch (s) {
      case 'B':
      case 'sen':
      case 'seoul':
      case '서울':
      case '서울특별시':
        return 'hes.sen.go.kr';
      case 'C':
      case 'pen':
      case 'busan':
      case '부산':
      case '부산광역시':
        return 'hes.pen.go.kr';
      case 'D':
      case 'dge':
      case 'daegu':
      case '대구':
      case '대구광역시':
      case '머구':
      case '대집트':
        return 'hes.dge.go.kr';
      case 'E':
      case 'ice':
      case 'incheon':
      case '인천':
      case '인천광역시':
      case '마계':
        return 'hes.ice.go.kr';
      case 'F':
      case 'gen':
      case 'gwangju':
      case '광주':
      case '광주광역시':
      case '팡주':
        return 'hes.gen.go.kr';
      case 'G':
      case 'dje':
      case 'daejeon':
      case '대전':
      case '대전광역시':
      case '머전':
        return 'hes.dje.go.kr';
      case 'H':
      case 'use':
      case 'ulsan':
      case '울산':
      case '울산광역시':
        return 'hes.use.go.kr';
      case 'I':
      case 'sje':
      case 'sejong':
      case '세종':
      case '세종시':
      case '세종특별자치시':
        return 'hes.sje.go.kr';
      case 'J':
      case 'goe':
      case 'gyeonggi':
      case '경기':
      case '경기도':
        return 'hes.goe.go.kr';
      case 'K':
      case 'gwe':
      case 'gangwon':
      case '강원':
      case '강원도':
        return 'hes.gwe.go.kr';
      case 'M':
      case 'cbe':
      case 'chungbuk':
      case '충북':
      case '충청북도':
        return 'hes.cbe.go.kr';
      case 'N':
      case 'cne':
      case 'chungnam':
      case '충남':
      case '충청남도':
        return 'hes.cne.go.kr';
      case 'P':
      case 'jbe':
      case 'jeonbuk':
      case '전북':
      case '전라북도':
        return 'hes.jbe.go.kr';
      case 'Q':
      case 'jne':
      case 'jeonnam':
      case '전남':
      case '전라남도':
        return 'hes.jne.go.kr';
      case 'R':
      case 'gbe':
      case 'gyeongbuk':
      case '경북':
      case '경상북도':
        return 'hes.gbe.kr';
      case 'S':
      case 'gne':
      case 'gyeongnam':
      case '경남':
      case '경상남도':
        return 'hes.gne.go.kr';
      case 'T':
      case 'jje':
      case 'jeju':
      case '제주':
      case '제주도':
      case '탐라':
      case '탐라국':
        return 'hes.jje.go.kr';
      default:
        return false;
    }
  };

  exports.get = function(school, year, month, callback) {
    var d, domain, host;
    d = new Date;
    if (!/^[B-KMNP-T][0-9]{9}$/.test(school)) {
      callback("Invalid or unknown code (" + school + ")", null);
      return;
    }
    switch (arguments.length) {
      case 2:
        callback = year;
        year = d.getFullYear();
        month = d.getMonth() + 1;
        break;
      case 4:
        if (!((0 < month && month <= 12))) {
          callback('Invalid month (1-12)', null);
          return;
        }
        break;
      default:
        callback('Invalid argument count', null);
        return;
    }
    domain = getDomain(school[0]);
    host = domain;
    if (domain === 'hes.jje.go.kr') {
      domain = '203.230.177.150';
    }
    jsdom.env({
      url: "http://" + domain + "/sts_sci_md00_001.do?schulCode=" + school + "&schulCrseScCode=4&schYm=" + year + "." + (zfill(month)),
      headers: {
        Host: host
      },
      QuerySelector: true,
      done: function(e, window) {
        var date, day, i, item, name, q, r, value, _i, _j, _len, _ref;
        if (e) {
          return callback("Request failed: " + (e.toString()), null);
        } else {
          r = {};
          q = window.document.querySelectorAll('.tbl_type3 td div');
          for (_i = 0, _len = q.length; _i < _len; _i++) {
            day = q[_i];
            if ((day == null) || !day.innerHTML.indexOf('<br>')) {
              continue;
            }
            day = day.innerHTML;
            date = day.substr(0, day.indexOf('<br>'));
            item = day.split(/(\[.+?\])/);
            r[date] = {};
            for (i = _j = 1, _ref = item.length - 1; _j <= _ref; i = _j += 2) {
              name = item[i].replace(/(\[|\])/g, '');
              value = item[i + 1].split('<br>').filter(Boolean);
              switch (name) {
                case '조식':
                  r[date].breakfast = value;
                  break;
                case '중식':
                  r[date].lunch = value;
                  break;
                case '석식':
                  r[date].dinner = value;
              }
            }
          }
          return callback(null, r);
        }
      }
    });
    return void 0;
  };

  exports.find = function(doe, query, callback) {
    var domain, host;
    domain = getDomain(doe);
    host = domain;
    if (!domain) {
      callback("No such dep: " + doe, null);
    }
    if (domain === 'hes.jje.go.kr') {
      domain = '203.230.177.150';
    }
    request({
      uri: "http://" + domain + "/spr_ccm_cm01_100.do?kraOrgNm=" + query,
      headers: {
        Host: host
      },
      json: true
    }, function(e, res, j) {
      var i, l, r, _i, _len;
      if (e) {
        callback("Request failed: " + e, null);
        return;
      }
      l = j.resultSVO.orgDVOList;
      r = [];
      for (_i = 0, _len = l.length; _i < _len; _i++) {
        i = l[_i];
        r.push({
          name: i.kraOrgNm,
          code: i.orgCode,
          type: i.schulCrseScCodeNm,
          address: i.zipAdres
        });
      }
      return callback(null, r);
    }).on('error', function(e) {
      return callback("Request failed: " + e, null);
    });
    return void 0;
  };

}).call(this);
